[workspace]
members = [
    "cli",
    "config",
    "utils",
    "perpetuals",
    "program",
    "jupiter_api"
]
resolver = "2"
[profile.release]
opt-level = 3
incremental = false
codegen-units = 1
lto = "fat"
[profile.release.build-override]
opt-level = 3
codegen-units = 1